CREATE OR REPLACE TABLE pois AS
SELECT DISTINCT
    ID_STORE, POI_CBG AS POI_GEOID, MSA_CODE AS CBSAFP,
    PERSISTENT_ID, BRAND, LOCATION_NAME,
    STREET_ADDRESS, CITY, REGION, ISO_COUNTRY_CODE,
    NAICS_CODE, TOP_CATEGORY, SUB_CATEGORY,
    OPEN_DATE, CLOSE_DATE,
    LONGITUDE, LATITUDE,
    ST_Point(LONGITUDE, LATITUDE) AS GEOM
FROM read_parquet('data/2025-weekly-patterns-plus/*.parquet', union_by_name=false)
WHERE MSA_CODE::VARCHAR IN (SELECT CBSAFP FROM cbsa_top)
ORDER BY ID_STORE;
