CREATE TABLE IF NOT EXISTS pois AS
SELECT DISTINCT
    ID_STORE, POI_CBG AS GEOID, PERSISTENT_ID, BRAND, LOCATION_NAME,
    STREET_ADDRESS, CITY, MSA_CODE, REGION, ISO_COUNTRY_CODE,
    TOP_CATEGORY, SUB_CATEGORY,
    OPEN_DATE, CLOSE_DATE,
    LONGITUDE, LATITUDE,
    ST_Point(LONGITUDE, LATITUDE) AS GEOM
FROM read_parquet('data/2025-weekly-patterns-plus/*.parquet', union_by_name=false);
